services:
  - type: cron
    name: pbi-tv-exporter
    runtime: python
    schedule: "*/5 * * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python export_pbi.py
    envVars:
      - key: PBI_USERNAME
        sync: false
      - key: PBI_PASSWORD
        sync: false
      - key: GIT_REPO_URL
        sync: false
      - key: GIT_TOKEN
        sync: false
